services:
    app:
        build: .
        restart: always
        tty: true
        container_name: ${SERVICE_NAME:-repair-business-app-development}
        ports:
            - "${SERVICE_PORT:-8000}:80"
        env_file:
            - .env
        networks:
            - app_network
networks:
  app_network:
    name: ${NETWORK_NAME:-default}
    external: true
