services:
    repair-business:
        build: .
        volumes:
            - ../:/app/
        restart: always
        tty: true
        container_name: "repair-business-app"
        ports:
        - "8000:8000"
        networks:
            - _constructor

#dev-network-with-database
networks:
    _constructor:
        external: true