services:
    repair-business:
        build: .
        volumes:
            - ../:/app/
        restart: always
        tty: true
        container_name: "repair-business-app"
        network_mode: "host"   